{
 "title": "Karapace",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Karapace Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Karapace Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "exception", "legendFormat": "{{where}} - {{exception}}" }
   ]
  },
  {
   "title": "Count by Exception",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "karapace_exceptions_sum_by_exception",
     "legendFormat": "exception={{exception}}"
    }
   ]
  },
  { "title": "Karapace HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "karapace_http_requests_total",
     "legendFormat": "instance={{instance}} method={{method}} path={{path}} status={{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "karapace_http_requests_duration_seconds_bucket",
     "legendFormat": "instance={{instance}} method={{method}} path={{path}}"
    }
   ]
  },
  {
   "title": "Karapace Schema Reader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subjects Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "karapace_schema_reader_subjects",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Schemas Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "karapace_schema_reader_schemas", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Records Processed by Keymode",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "karapace_schema_reader_records_processed",
       "legendFormat": "{{keymode}}"
      }
     ]
    },
    {
     "title": "Records by Keymode",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "karapace_schema_reader_records_per_keymode",
       "legendFormat": "{{keymode}}"
      }
     ]
    },
    {
     "title": "Schema reader schema versions by state",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "karapace_schema_reader_subject_data_schema_versions",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}