apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file karapace-main/container/compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_PATHS_PROVISIONING
              value: /grafana/provisioning
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: karapace
            - name: GF_SECURITY_ADMIN_USER
              value: karapace
          image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /grafana/dashboards
              name: grafana-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: grafana-cm0
          name: grafana-cm0
