apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
    - name: "9101"
      port: 9101
      targetPort: 9101
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: kafka
