apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file karapace-main/container/compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_BROKER_RACK
              value: local
            - name: KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL
              value: http://karapace-registry:8081
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_INTER_BROKER_PROTOCOL_VERSION
              value: "2.4"
            - name: KAFKA_JMX_HOSTNAME
              value: localhost
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_LOG_CLEANER_ENABLE
              value: "true"
            - name: KAFKA_LOG_MESSAGE_FORMAT_VERSION
              value: "2.4"
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "300000"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "209715200"
            - name: KAFKA_NUM_IO_THREADS
              value: "8"
            - name: KAFKA_NUM_NETWORK_THREADS
              value: "112"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR
              value: "1"
            - name: KAFKA_NUM_REPLICA_FETCHERS
              value: "4"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
              value: "102400"
            - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
              value: "104857600"
            - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
              value: "102400"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS
              value: "16"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "6000"
          image: confluentinc/cp-kafka:latest
          name: kafka
          ports:
            - containerPort: 9101
              protocol: TCP
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
