apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: karapace-rest
  name: karapace-rest
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: karapace-rest
