apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: karapace-registry
  name: karapace-registry
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: karapace-registry
