apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: statsd-exporter
  name: statsd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: statsd-exporter
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file karapace-main/container/compose.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: statsd-exporter
    spec:
      containers:
        - args:
            - --statsd.listen-udp=:8125
            - --web.listen-address=:9102
          image: prom/statsd-exporter
          name: statsd-exporter
          ports:
            - containerPort: 9102
              protocol: TCP
            - containerPort: 8125
              protocol: UDP
      restartPolicy: Always
