apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file karapace-main/container/compose.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: statsd-exporter
  name: statsd-exporter
spec:
  ports:
    - name: "9102"
      port: 9102
      targetPort: 9102
    - name: "8125"
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    io.kompose.service: statsd-exporter
